string robot_info


# {
#  "1": {
#    "Pose2D": {            # in meters (Float32)
#      "x": 0, 
#      "y": 0,
#      "z": 0,
#      "theta": 0.0
#    },
#    "topo":{
#      "previous_node": 1,    # previous node id (Int)
#      "next_node": 2,        # now or next node id (Int)
#    },
#    "battery_level": 85,     # battery percentage (Int)
#    "status": "idle"         # idle, busy, charging (Str)
#  },
#  "2": {
#    "position": {
#      "x": 0, 
#      "y": 0,
#      "z": 0
#    },
#    "orientation": {
#      "rx": 0,
#      "ry": 0,
#      "rz": 0
#    },
#    "topo":{
#      "previous_node": 1, 
#      "next_node": 2,
#    },
#    "battery_level": 85,
#    "status": "idle"
#  },
# }